<!-- header.inc -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
     <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
     <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
     <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
    
    <link rel="Stylesheet"  type="text/css"  href="Style.css">

    <link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0"  rel="stylesheet">
   <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Exo:wght@400;700&display=swap">

    <link href="https://fonts.googleapis.com/css2?family=Exo:wght@100&family=Permanent+Marker&family=Ysabeau+SC:wght@600;900&display=swap" rel="stylesheet">


     
    <script src="main.js"></script>
    <title><?= $title ?></title>
</head>
<body class="container-fluid">



<!-- end of header.inc -->